### ISSUE TITLE
Unexpected input(s) 'auto-update-conda', valid inputs are ['activate-conda', 'update-conda', 'python-version', 'conda-channels']

### ISSUE THREAD

**Issue by Bengt** [s-weigand/setup-conda#117]
**Describe the bug**

I get a warning about a non-existent input.

**To Reproduce**

```yaml
Run s-weigand/setup-conda@v1
  with:
    activate-conda: false
    auto-update-conda: true
    python-version: 3.6
    update-conda: false
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.6.8\x64
    TOXENV: py36-windows
```

**Expected behavior**

Setting up conda works without any warning.

**Environment**

 - OS: windows-latest

**Additional context**

It worked in the past, but has recently been broken.

**Comment by Bengt** [comment]
Should I maybe be using the `update-conda` input instead now?

**Comment by s-weigand** [comment]
> It worked in the past, but has recently been broken.

This is strange, since `auto-update-conda` was never a [valid input](https://github.com/s-weigand/setup-conda/commit/2a7e5def4266ae0904e5367796d3389cb468ce95?short_path=b335630) and the [last release was over 6 months ago](https://github.com/s-weigand/setup-conda/releases/tag/v1.0.5).
So maybe before the runners did simply ignore unused inputs and now they error.

> Should I maybe be using the `update-conda` input instead now?

Yap, that is the way to go😃

**Comment by s-weigand** [comment]
Also, since you use 
```yaml
  activate-conda: false
```
there shouldn't be a need to set
```yaml
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.6.8\x64
```

And you could simply use [`actions/setup-python`](https://github.com/actions/setup-python)
So your workflow you'd simplify to:
```yaml
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
```
As a little side note I use `activate-conda: false`, when I need coda to get binaries like `pandoc` installed cross-platform but use `actions/setup-python` to set python since it only changes the `PATH` variable, while conda needs to download the python version if `python-version` isn't `default`.
