### ISSUE TITLE
env activation is not persistent throughout the session

### ISSUE THREAD

**Issue by basic-ph** [s-weigand/setup-conda#12]
**Describe the bug**
If the command `source activate <env-name>` is executed in a previous _step_ respect to one in which the environment is used, the env itself does **not** result activated and raise for using a command that is not installed in the base env.

**To Reproduce**
the actual YAML file with the workflow:
```yaml
name: CI
on: push

jobs:
  test:
    name: Pytest Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conda setup
        uses: s-weigand/setup-conda@v1.0.3
        with:
          update-conda: true
          python-version: 3.7
      # env activation as suggested by @s-weigand
      - name: Conda environment creation
        run: |
          conda env create -f environment.yml
          source activate feat
          pip install -e .
      - name: Testing with pytest
        run: |
          pytest
```
the following error is reported in the Actions log:
```
2020-05-19T17:38:50.4263319Z ##[group]Run pytest
2020-05-19T17:38:50.4263646Z [36;1mpytest[0m
2020-05-19T17:38:50.4299399Z shell: /bin/bash -e {0}
2020-05-19T17:38:50.4299513Z ##[endgroup]
2020-05-19T17:38:50.4377171Z /home/runner/work/_temp/5ded05d7-e2df-43db-bfca-4721d3e5faea.sh: line 1: pytest: command not found
2020-05-19T17:38:50.4384238Z ##[error]Process completed with exit code 127.
```

**Workaround**
At the moment the only way I found to make it work is to run `source activate feat` also before the usage of the environment (in my case `pytest` command) like this:
```yaml
name: CI
on: push

jobs:
  test:
    name: Pytest Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conda setup
        uses: s-weigand/setup-conda@v1.0.3
        with:
          update-conda: true
          python-version: 3.7
      # env activation as suggested by @s-weigand
      - name: Conda environment creation
        run: |
          conda env create -f environment.yml
          source activate feat
          pip install -e .
      - name: Testing with pytest
        run: |
          source activate feat
          pytest
```
