### ISSUE TITLE
failing action, bioconda channel not available

### ISSUE THREAD

**Issue by violafanfani** [s-weigand/setup-conda#235]
**Describe the bug**
I use the action to test and release a python package with the gihub CI. Lest week all worked correctly, but I am now getting an error:
`UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel  bioconda <https://conda.anaconda.org/ bioconda>` when creating the environment (`/usr/share/miniconda/bin/conda create -y -n __setup_conda python=3.9`). The bioconda channels doesn't seem to be down, as I tried generating the same environment on my local machine.

**To Reproduce**
1. Go to netzoopy actions : 'https://github.com/netZoo/netZooPy/runs/6628979901?check_suite_focus=true'
2. Click on 'actions'
3. Scroll down to `test conda #44`

**Expected behavior**
The rule is supposed to run with no errors.

**Additional context**

Rule in CI:
```
      - name: "Setup Conda"
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, bioconda
```

Entire error:
```
Installing conda python 3.9
  /usr/share/miniconda/bin/conda create -y -n __setup_conda python=3.9
  Collecting package metadata (current_repodata.json): ...working... failed
  
  UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel  bioconda <https://conda.anaconda.org/ bioconda>
  
  The channel is not accessible or is invalid.
  
  You will need to adjust your conda configuration to proceed.
  Use `conda config --show channels` to view your configuration's current state,
  and use `conda config --show-sources` to view config file locations.
  
  
  Error: The process '/usr/share/miniconda/bin/conda' failed with exit code 1
```
