### ISSUE TITLE
(feat): Add caching flag

### ISSUE THREAD

**Issue by s-weigand** [s-weigand/setup-conda#3]
Caching would improve the speed for installions, so it should be a built in setting.

**Comment by bryant1410** [comment]
You can do something like:

```yml
    - uses: actions/cache@v1
      with:
        path: /usr/share/miniconda
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
```
