### ISSUE TITLE
Setup error on macOS-latest when adding conda path to PATH (received undefined)

### ISSUE THREAD

**Issue by pauleve** [s-weigand/setup-conda#432]
Running `s-weigand/setup-conda@v1` on `macOS-latest` with default options fails at the step "Adding conda path to PATH" with   `Error: The "path" argument must be of type string. Received undefined`

Recipe is
```
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
        env:
            OLD_REF: ${{ github.event.before }}
            ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        steps:
            - uses: s-weigand/setup-conda@v1
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: bash auto-build-from-push.sh
```
(src: https://github.com/colomoto/colomoto-conda/blob/master/.github/workflows/push.yml)

Log is 
```
Getting original pythonLocation
  /usr/bin/which python
  /Library/Frameworks/Python.framework/Versions/Current/bin/python
Adding conda path to PATH
  undefined
  Error: The "path" argument must be of type string. Received undefined
```
(src: https://github.com/colomoto/colomoto-conda/actions/runs/8986528695/job/24682859612)

Not sure what I'm doing wrong here, and it was working fine until recently..
