### ISSUE TITLE
Error in conda setup

### ISSUE THREAD

**Issue by kujaku11** [s-weigand/setup-conda#495]
**Describe the bug**

An error is encountered when setting up a conda environment using GitActions. This worked 3 weeks ago, but does not now.   Similar to issue #180   

`Error: Unable to process file command 'env' successfully.`
`Error: Invalid format 'unset _CE_M'`

The log is:

```
Run s-weigand/setup-conda@v1.2.3
  with:
    update-conda: false
    python-version: [3](https://github.com/kujaku11/mt_metadata/actions/runs/13572472093/job/37941032243#step:3:3).8
    activate-conda: true
Getting original pythonLocation
  /usr/bin/which python
  /usr/bin/python
Adding conda path to PATH
  The CONDA env var is: /usr/share/miniconda
Installing conda python 3.[8](https://github.com/kujaku11/mt_metadata/actions/runs/13572472093/job/37941032243#step:3:9)
Activating conda __setup_conda
  Conda activate script:
  /usr/share/miniconda/bin/conda shell.bash activate __setup_conda
  unset _CE_M
  unset _CE_CONDA
  PS1='(__setup_conda) '
  export PATH='/usr/share/miniconda/envs/__setup_conda/bin:/usr/share/miniconda/condabin:/usr/share/miniconda/bin:/usr/share/miniconda:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
  export CONDA_PREFIX='/usr/share/miniconda/envs/__setup_conda'
  export CONDA_SHLVL='1'
  export CONDA_DEFAULT_ENV='__setup_conda'
  export CONDA_PROMPT_MODIFIER='(__setup_conda) '
  export CONDA_EXE='/usr/share/miniconda/bin/conda'
  export CONDA_PYTHON_EXE='/usr/share/miniconda/bin/python'
  
  
  Data used for activation:
   {
    condaPaths: [
      '/usr/share/miniconda',
      '/usr/share/miniconda/bin',
      '/usr/share/miniconda/condabin',
      '/usr/share/miniconda/envs/__setup_conda/bin'
    ],
    envVars: {
      'unset _CE_M\nunset _CE_CONDA\nPS1': '(__setup_conda) ',
      CONDA_PREFIX: '/usr/share/miniconda/envs/__setup_conda',
      CONDA_DEFAULT_ENV: '__setup_conda',
      CONDA_PROMPT_MODIFIER: '(__setup_conda) ',
      CONDA_EXE: '/usr/share/miniconda/bin/conda',
      CONDA_PYTHON_EXE: '/usr/share/miniconda/bin/python'
    }
  }

Error: Unable to process file command 'env' successfully.
Error: Invalid format 'unset _CE_M'
```

The full log is here: https://github.com/kujaku11/mt_metadata/actions/runs/13572472093/job/37941032243.

The workflow yml is:

```
name: TestingInConda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1.2.3
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda create -n mtmetadata-test python=${{ matrix.python-version }}
        source activate mtmetadata-test
        conda install pytest
        conda install pytest-cov
        
    - name: Install Our Package
      shell: bash
      run: |
        source activate mtmetadata-test
        pip install -e .
        conda list
    - name: Run Tests
      shell: bash
      run: |
        source activate mtmetadata-test
        pytest --cov=./ --cov-report=xml --cov=mt_metadata
        
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        verbose: true
        flags: tests
```

If I use `s-weigand/setup-conda@v1.0.7` all tests pass except for Python 3.8, but that looks like a conda issue.
