### ISSUE TITLE
Allow option to setup my own environment with environment.yml

### ISSUE THREAD

**Issue by UnHumbleBen** [s-weigand/setup-conda#6]
**Is your feature request related to a problem? Please describe.**
It is not clear how to activate my own requirement
**Describe the solution you'd like**
I have a `environment.yml` file in my repository. I would like to run these commands
```
conda env create -f environment.yml
source ~/anaconda3/etc/profile.d/conda.sh
conda activate my_env
```

Currently, the second command does not work because it is not the correct path to conda.sh. I would like documentation for where the conda.sh file is located.

**Describe alternatives you've considered**
I have not found an alternative

**Comment by basic-ph** [comment]
I got stuck on the same issue during the Christmas holiday and during an email conversation with @s-weigand he suggested to me the use of `source activate my_env`.
Here's my Github action YAML file as an example:
```
name: CI
on: push

jobs:
  test:
    name: Pytest Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conda setup
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.7
      # env activation as suggested by @s-weigand
      - name: Conda environment creation	
        run: |
          conda env create -f environment.yml	
          source activate feat	
          pip install -e .
      # env activation as it should be
      # - name: Conda environment creation	
      #   run: |
      #     conda env create -f environment.yml	
      #     conda activate feat	
      #     pip install -e .
      - name: Testing with pytest
        run: |
          source activate feat
          pytest
© 2020 GitHub, Inc.
```
Let us know if it works also for you.

PS: I think Sebastian is planning to add two more options to deal with this type of situations:
- the choice of which shell initialize for conda usage (see [here](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell)),
- the setting to indicate a conda environment YAML file.
