### ISSUE TITLE
GDAL 3 Environment variables not being set

### ISSUE THREAD

**Issue by dcdenu4** [s-weigand/setup-conda#7]
**Describe the bug**

Using **setup-conda** to install gdal 3+ on Ubuntu 18.04 and noticed **GDAL_DATA** and **PROJ_LIB** environment variables are not being set. This was noticed by getting the following error in one of our tests for a Python project when trying to use the gdal library:
`ERROR 1: PROJ: proj_create_from_database: Open of /usr/share/miniconda/share/proj failed`

When setting **GDAL_DATA** and **PROJ_LIB** environment variables in a *yml* workflow manually, calling `printenv` will show the paths to those variables, however, from the test in Python, printing `os.environ` shows that these variables are still not present or set (see screeshots).

**To Reproduce**
1. Create a Github Actions workflow with OS as Ubuntu 18.04
2. Use setup-conda and install gdal3+ from a requirements file
3. Run a Python file that imports gdal and osr to load a EPSG Code

From dcdenu4/gdal3-conda-setup,  **.github/workflow/pythonpackage.yml** :
```
name: Test PyGeoprocessing

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    env:
        PACKAGES: "pytest flake8"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
      with:
          # Fetch all history so that setuptool_scm can build the correct version string.
          fetch-depth: 0

    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.2
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}
        activate-conda: true
        conda-channels: anaconda, conda-forge
    - name: Install dependencies
      shell: bash
      run: conda upgrade -y pip setuptools

    - name: Install GDAL3 Test (Linux)
      env: 
          GDAL_DATA: /usr/share/miniconda/share/gdal/
          PROJ_LIB: /usr/share/miniconda/share/proj/
      run: |
          conda install --file requirements.txt
          conda install $PACKAGES
          printenv
          find /usr -name proj.db 
          ls -l /usr/share/miniconda/share/proj/

    - name: Test with pytest
      run: pytest -s
```

**Expected behavior**
I would expect **GDAL_DATA** and **PROJ_LIB** to be set as environment variables and to be available to Python to run the GDAL Library.

**Screenshots**
Environment variables printed out using `printenv` after install gdal and manually setting environment variables. If not manually set, **GDAL_DATA** and **PROJ_LIB** do not appear here.
![image](https://user-images.githubusercontent.com/2659980/76118938-569f6b00-5fbc-11ea-91d4-6162829dcc00.png)

A Python test using `os.environ` to show environment variables. **GDAL_DATA** and **PROJ_LIB** not present and error occurs.
![image](https://user-images.githubusercontent.com/2659980/76119020-7cc50b00-5fbc-11ea-9cf9-30c75b3ba42b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 via Github Actions VM
 - Browser [N / A]
 - Version [N / A]

**Additional context**
I created a dummy repo here: github.com/dcdenu4/gdal-conda-setup to help demonstrate this issue. Ultimately this problem has arisen from trying to go from **GDAL 2** to **GDAL 3** in a larger project, where using **GDAL 3** our tests fail using this kind of workflow.
